### ISSUE TITLE
Upgrading from web interface broke installation

### ISSUE THREAD

**Issue by Chaprnks** [SergiX44/XBackBone#118]
In the admin settings, I clicked check update. Showed 3.0.2 & I clicked upgrade installation. Now any URL pointing to the base_url shows ERR_TOO_MANY_REDIRECTS. I tested LICENSE file, to see if the URL was pointing to the correct spot.

![IsrLsKU](https://user-images.githubusercontent.com/6340970/70370260-0d436080-1893-11ea-8ab4-d13e09d0c330.png)

**Comment by Chaprnks** [comment]
I also checked the apache2.logs & found some that may be relivent.

`[Sat Dec 07 01:08:45.807866 2019] [php7:error] [pid 3235] [client 24.176.51.112:3023] PHP Fatal error:  Uncaught Slim\\Exception\\HttpNotFoundException: Not found. in /var/www/bb/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php:91\nStack trace:\n#0 /var/www/bb/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(57): Slim\\Middleware\\RoutingMiddleware->performRouting(Object(GuzzleHttp\\Psr7\\ServerRequest))\n#1 /var/www/bb/vendor/slim/slim/Slim/MiddlewareDispatcher.php(132): Slim\\Middleware\\RoutingMiddleware->process(Object(GuzzleHttp\\Psr7\\ServerRequest), Object(Slim\\Routing\\RouteRunner))\n#2 /var/www/bb/vendor/slim/slim/Slim/MiddlewareDispatcher.php(73): class@anonymous->handle(Object(GuzzleHttp\\Psr7\\ServerRequest))\n#3 /var/www/bb/vendor/slim/slim/Slim/App.php(208): Slim\\MiddlewareDispatcher->handle(Object(GuzzleHttp\\Psr7\\ServerRequest))\n#4 /var/www/bb/vendor/slim/slim/Slim/App.php(192): Slim\\App->handle(Object(GuzzleHttp\\Psr7\\ServerRequest))\n#5 /var/www/bb/install/index.php(232): Slim\\App->run()\n#6 {main}\n  thrown in /var/www/bb/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php on line 91, referer: http://bb.gta.sh//system
[Sat Dec 07 01:08:48.925650 2019] [php7:error] [pid 1818] [client 24.176.51.112:3025] PHP Fatal error:  Uncaught Slim\\Exception\\HttpNotFoundException: Not found. in /var/www/bb/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php:91\nStack trace:\n#0 /var/www/bb/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(57): Slim\\Middleware\\RoutingMiddleware->performRouting(Object(GuzzleHttp\\Psr7\\ServerRequest))\n#1 /var/www/bb/vendor/slim/slim/Slim/MiddlewareDispatcher.php(132): Slim\\Middleware\\RoutingMiddleware->process(Object(GuzzleHttp\\Psr7\\ServerRequest), Object(Slim\\Routing\\RouteRunner))\n#2 /var/www/bb/vendor/slim/slim/Slim/MiddlewareDispatcher.php(73): class@anonymous->handle(Object(GuzzleHttp\\Psr7\\ServerRequest))\n#3 /var/www/bb/vendor/slim/slim/Slim/App.php(208): Slim\\MiddlewareDispatcher->handle(Object(GuzzleHttp\\Psr7\\ServerRequest))\n#4 /var/www/bb/vendor/slim/slim/Slim/App.php(192): Slim\\App->handle(Object(GuzzleHttp\\Psr7\\ServerRequest))\n#5 /var/www/bb/install/index.php(232): Slim\\App->run()\n#6 {main}\n  thrown in /var/www/bb/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php on line 91
[Sat Dec 07 01:11:45.160281 2019] [php7:error] [pid 2160] [client 24.176.51.112:3145] PHP Fatal error:  Uncaught Slim\\Exception\\HttpNotFoundException: Not found. in /var/www/bb/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php:91\nStack trace:\n#0 /var/www/bb/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(57): Slim\\Middleware\\RoutingMiddleware->performRouting(Object(GuzzleHttp\\Psr7\\ServerRequest))\n#1 /var/www/bb/vendor/slim/slim/Slim/MiddlewareDispatcher.php(132): Slim\\Middleware\\RoutingMiddleware->process(Object(GuzzleHttp\\Psr7\\ServerRequest), Object(Slim\\Routing\\RouteRunner))\n#2 /var/www/bb/vendor/slim/slim/Slim/MiddlewareDispatcher.php(73): class@anonymous->handle(Object(GuzzleHttp\\Psr7\\ServerRequest))\n#3 /var/www/bb/vendor/slim/slim/Slim/App.php(208): Slim\\MiddlewareDispatcher->handle(Object(GuzzleHttp\\Psr7\\ServerRequest))\n#4 /var/www/bb/vendor/slim/slim/Slim/App.php(192): Slim\\App->handle(Object(GuzzleHttp\\Psr7\\ServerRequest))\n#5 /var/www/bb/install/index.php(232): Slim\\App->run()\n#6 {main}\n  thrown in /var/www/bb/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php on line 91
[Sat Dec 07 01:20:45.277051 2019] [php7:error] [pid 1817] [client 201.202.113.18:53753] script '/var/www/wp-login.php' not found or unable to stat
[Sat Dec 07 01:44:21.739405 2019] [php7:error] [pid 1815] [client 24.176.51.112:3515] PHP Fatal error:  Uncaught Slim\\Exception\\HttpNotFoundException: Not found. in /var/www/bb/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php:91\nStack trace:\n#0 /var/www/bb/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(57): Slim\\Middleware\\RoutingMiddleware->performRouting(Object(GuzzleHttp\\Psr7\\ServerRequest))\n#1 /var/www/bb/vendor/slim/slim/Slim/MiddlewareDispatcher.php(132): Slim\\Middleware\\RoutingMiddleware->process(Object(GuzzleHttp\\Psr7\\ServerRequest), Object(Slim\\Routing\\RouteRunner))\n#2 /var/www/bb/vendor/slim/slim/Slim/MiddlewareDispatcher.php(73): class@anonymous->handle(Object(GuzzleHttp\\Psr7\\ServerRequest))\n#3 /var/www/bb/vendor/slim/slim/Slim/App.php(208): Slim\\MiddlewareDispatcher->handle(Object(GuzzleHttp\\Psr7\\ServerRequest))\n#4 /var/www/bb/vendor/slim/slim/Slim/App.php(192): Slim\\App->handle(Object(GuzzleHttp\\Psr7\\ServerRequest))\n#5 /var/www/bb/install/index.php(232): Slim\\App->run()\n#6 {main}\n  thrown in /var/www/bb/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php on line 91
`
