### ISSUE TITLE
Size limit? (bug)

### ISSUE THREAD

**Issue by untuned** [SergiX44/XBackBone#15]
I've noticed that somewhat large files error out with a 400 bad request error.

```
Message:
The remote server returned an error: (400) Bad Request.

Request URL:
https://XXXXXXXXX/upload

Response:
{"message":"Token not specified."}

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)
```

The only problem is that the token *is* specified.

**Comment by SergiX44** [comment]
The maximum file size upload is determinated by the post_max_size and upload_max_filesize your in php.ini settings (You can see those logging in into the admin account > System).
![image](https://user-images.githubusercontent.com/4172890/51627226-c0d48800-1f41-11e9-94a5-89ce02aa3524.png)

Which version of xbackbone?
How are set those php.ini in your settings?
How much do you mean with "large file"?
