### ISSUE TITLE
I get a error when I try to upload using share-x

### ISSUE THREAD

**Issue by lebon1377** [SergiX44/XBackBone#163]
Response parse failed.
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.Linq.JToken.ReadFrom(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JToken.Parse(String json, JsonLoadSettings settings)
   at ShareX.UploadersLib.CustomUploaderParser.ParseSyntaxJson(String syntaxJsonPath)
   at ShareX.UploadersLib.CustomUploaderParser.ParseSyntax(String syntax, Boolean isOutput)
   at ShareX.UploadersLib.CustomUploaderParser.Parse(String text, Boolean isOutput)
   at ShareX.UploadersLib.CustomUploaderItem.ParseResponse(UploadResult result, ResponseInfo responseInfo, CustomUploaderInput input, Boolean isShortenedURL)
   at ShareX.UploadersLib.ImageUploaders.CustomImageUploader.Upload(Stream stream, String fileName)
<html><body><script type="text/javascript" src="/aes.js" ></script><script>function toNumbers(d){var e=[];d.replace(/(..)/g,function(d){e.push(parseInt(d,16))});return e}function toHex(){for(var d=[],d=1==arguments.length&&arguments[0].constructor==Array?arguments[0]:arguments,e="",f=0;f<d.length;f++)e+=(16>d[f]?"0":"")+d[f].toString(16);return e.toLowerCase()}var a=toNumbers("f655ba9d09a112d4968c63579db590b4"),b=toNumbers("98344c2eee86c3994890592585b49f80"),c=toNumbers("ebd49491f97a69b6a15efda2ac46b4f1");document.cookie="__test="+toHex(slowAES.decrypt(c,2,a,b))+"; expires=Thu, 31-Dec-37 23:55:55 GMT; path=/"; location.href="https://cdn.lebyy.cf/upload?i=1";</script><noscript>This site requires Javascript to work, please enable Javascript in your browser or use a browser with Javascript support</noscript></body></html>

**Comment by lebon1377** [comment]
**Javascript is enabled in my browser.**

**Comment by lebon1377** [comment]
**Fixed** It was my hosting's problem thank you!

**Comment by lebon1377** [comment]
Closing this issue.
