### ISSUE TITLE
install git + php7.4+ FATAL error: "Uncaught TypeError: Argument 1 passed to dsnFromConfig() must be of the type array"

### ISSUE THREAD

**Issue by pgnd** [SergiX44/XBackBone#217]
installing,
```
git log -n1
	1 commit 45cea0e794f55b09af5bda05b81d17bddca4badc (HEAD -> master, origin/master, origin/HEAD)
	2 Merge: 1d0f5b1 18911de
	3 Author: Sergio Brighenti <sergio@brighenti.me>
	4 Date:   Thu May 14 13:41:17 2020 +0200
	5
	6     Merge pull request #216 from camjac251/master
	7
	8     Add S3 Endpoint Support
```

with,
```
php -v
	PHP 7.4.6-dev (cli) (built: Apr 12 2020 19:23:21) ( NTS )
	Copyright (c) The PHP Group
	Zend Engine v3.4.0, Copyright (c) Zend Technologies
	    with Zend OPcache v7.4.6-dev, Copyright (c), by Zend Technologies

nginx -v
	nginx version: nginx/1.18.0 (pgnd Build)

sqlite3 --version
	3.31.1 2020-01-27 19:55:54 3bfa9cc97da10598521b342961df8f5f68c7388fa117345eeb516eaa837balt1
```

on install/exec,
```
composer install
php bin/migrate --install
```

fails,
```
return [
        'base_url' => 'https://xbackbone.example.com',
        'storage' => [
                'driver' => 'local',
                'path' => '/srv/data/xbackbone',
        ],
        'db' => [
                'connection' => 'sqlite',
                'dsn' => '/srv/db/xbackbone/xbackbone.db',
                'username' => null, // username and password not needed for sqlite
                'password' => null,
        ]
];
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to dsnFromConfig() must be of the type array, int given, called in /srv/apps/XBackBone/bootstrap/container.php on line 41 and defined in /srv/apps/XBackBone/app/helpers.php:467
Stack trace:
#0 /srv/apps/XBackBone/bootstrap/container.php(41): dsnFromConfig(1)
#1 [internal function]: DI\Definition\Source\DefinitionFile->{closure}(Object(DI\Container))
#2 /srv/apps/XBackBone/vendor/php-di/invoker/src/Invoker.php(82): call_user_func_array(Object(Closure), Array)
#3 /srv/apps/XBackBone/vendor/php-di/php-di/src/Definition/Resolver/FactoryResolver.php(80): Invoker\Invoker->call(Object(Closure), Array)
#4 /srv/apps/XBackBone/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(64): DI\Definition\Resolver\FactoryResolver->resolve(Object(DI\Definition\FactoryDefinition), Array)
#5 /srv/apps/XBackBone/vendor/php-di/php-di/src/Container.php(387): DI\Definition\Resolver\ResolverDispatcher->resolve(Object(DI\Definition\FactoryDefinition), Arra in /srv/apps/XBackBone/app/helpers.php on line 467
```

**Comment by SergiX44** [comment]
How did you write the config file? The config seems was not loaded or somewhat not right.

**Comment by pgnd** [comment]
ugh.
you are correct.
non-ascii garbage in my config.  clean config -> no problem.

clearly PEBKAC.

sry for the noise; closing.
