### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ClumsyYT** [SergiX44/XBackBone#22]
**System Info**
+ PHP Version: 7.3
+ XBackBone Version: Newest
+ Webserver: Apache 2.4.37

I am getting a Slim Application Error. I checked the error log and i am erroring out at like 318

ERROR OUTPUT:
[09-Feb-2019 22:17:26 America/New_York] Slim Application Error:
Type: Error
Message: Class 'finfo' not found
File: /home/killxfil/hangyourself.live/vendor/league/flysystem/src/Adapter/Local.php
Line: 318
Trace: #0 /home/killxfil/hangyourself.live/vendor/league/flysystem/src/Filesystem.php(284): League\Flysystem\Adapter\Local->getMimetype('297a4/5c5f97c34...')
#1 /home/killxfil/hangyourself.live/app/Controllers/UploadController.php(319): League\Flysystem\Filesystem->getMimetype('297a4/5c5f97c34...')
#2 /home/killxfil/hangyourself.live/app/Controllers/UploadController.php(100): App\Controllers\UploadController->streamMedia(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(League\Flysystem\Filesystem), Object(stdClass))
#3 [internal function]: App\Controllers\UploadController->show(Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#4 /home/killxfil/hangyourself.live/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(41): call_user_func(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#5 /home/killxfil/hangyourself.live/vendor/slim/slim/Slim/Route.php(356): Slim\Handlers\Strategies\RequestResponse->__invoke(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#6 /home/killxfil/hangyourself.live/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#7 /home/killxfil/hangyourself.live/vendor/slim/slim/Slim/Route.php(334): Slim\Route->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#8 /home/killxfil/hangyourself.live/vendor/slim/slim/Slim/App.php(516): Slim\Route->run(Object(Slim\Http\Request), Object(Slim\Http\Response))
#9 /home/killxfil/hangyourself.live/bootstrap/app.php(127): Slim\App->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#10 [internal function]: Closure->{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\App))
#11 /home/killxfil/hangyourself.live/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array(Object(Closure), Array)
#12 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\App))
#13 /home/killxfil/hangyourself.live/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\App))
#14 /home/killxfil/hangyourself.live/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response))
#15 /home/killxfil/hangyourself.live/vendor/slim/slim/Slim/App.php(407): Slim\App->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#16 /home/killxfil/hangyourself.live/vendor/slim/slim/Slim/App.php(315): Slim\App->process(Object(Slim\Http\Request), Object(Slim\Http\Response))
#17 /home/killxfil/hangyourself.live/index.php(8): Slim\App->run()
#18 {main}
View in rendered output by enabling the "displayErrorDetails" setting.

**Comment by ClumsyYT** [comment]
FIXED IT I HAD TO ENABLE THE FILEINFO EXTENSION!!
