### ISSUE TITLE
Install Errors with Not Writable Directories

### ISSUE THREAD

**Issue by joshcsullivan** [SergiX44/XBackBone#228]
**System Info**
+ PHP Version: 7.2
+ XBackBone Version: 3.1.4
+ Webserver: Apache
+ Database backend: N/A (will be SQLite)

**Describe the bug**
I have an apache server running a site, I tried to add XbackBone as a sub directory, and I'm getting this error when navigating to the site to install:

```
The cache folder is not writable (/var/www/example.com/public_html/xbb/install/../resources/cache)
The database folder is not writable (/var/www/example.com/public_html/xbb/install/../resources/database)
The sessions folder is not writable (/var/www/example.com/public_html/xbb/install/../resources/sessions)
```

Not the most familiar with PHP/apache, but able to muddle my way through usually. I've tried changing folder permissions to no avail. Any help would be appreciated.

**To Reproduce**
1. Open example.com/xbb/install

**Expected behavior**
No errors

**Screenshots**
![image](https://user-images.githubusercontent.com/5774100/83914913-2d6bb380-a740-11ea-9634-12f4b025594f.png)

**Logs**
XBackBone and/or webserver logs.

**Comment by joshcsullivan** [comment]
Made a little progress, I found the permissions issue and resolved it.

Now when I fill out the install page, it gives an HTTP 500 error and the apache2 error log has these entries:

```
[Fri Jun 05 20:04:31.444384 2020] [php7:error] [pid 1027] [client x.x.x.x:60017] PHP Fatal error:  Uncaught League\\Flysystem\\Exception: Impossible to create the root directory "/var/www/example.com/public_html/storage". mkdir(): Permission denied in /var/www/example.com/public_html/vendor/league/flysystem/src/Adapter/Local.php:112\nStack trace:\n#0 /var/www/example.com/public_html/vendor/league/flysystem/src/Adapter/Local.php(78): League\\Flysystem\\Adapter\\Local->ensureDirectory('/var/www/lnks.d...')\n#1 /var/www/example.com/public_html/bootstrap/container.php(49): League\\Flysystem\\Adapter\\Local->__construct('/var/www/lnks.d...')\n#2 [internal function]: DI\\Definition\\Source\\DefinitionFile->{closure}(Object(DI\\Container))\n#3 /var/www/example.com/public_html/vendor/php-di/invoker/src/Invoker.php(82): call_user_func_array(Object(Closure), Array)\n#4 /var/www/example.com/public_html/vendor/php-di/php-di/src/Definition/Resolver/FactoryResolver.php(80): Invoker\\Invoker->call(Object(Closure), Array)\n#5 /var/www/example.com/public_html/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(64): DI\\Definition\\Resolver\\FactoryRe in /var/www/example.com/public_html/vendor/league/flysystem/src/Adapter/Local.php on line 112, referer: https://example.com/install/
[Fri Jun 05 20:04:36.793205 2020] [php7:error] [pid 1026] [client x.x.x.x:60018] PHP Fatal error:  Uncaught League\\Flysystem\\Exception: Impossible to create the root directory "/var/www/example.com/public_html/storage". mkdir(): Permission denied in /var/www/example.com/public_html/vendor/league/flysystem/src/Adapter/Local.php:112\nStack trace:\n#0 /var/www/example.com/public_html/vendor/league/flysystem/src/Adapter/Local.php(78): League\\Flysystem\\Adapter\\Local->ensureDirectory('/var/www/lnks.d...')\n#1 /var/www/example.com/public_html/bootstrap/container.php(49): League\\Flysystem\\Adapter\\Local->__construct('/var/www/lnks.d...')\n#2 [internal function]: DI\\Definition\\Source\\DefinitionFile->{closure}(Object(DI\\Container))\n#3 /var/www/example.com/public_html/vendor/php-di/invoker/src/Invoker.php(82): call_user_func_array(Object(Closure), Array)\n#4 /var/www/example.com/public_html/vendor/php-di/php-di/src/Definition/Resolver/FactoryResolver.php(80): Invoker\\Invoker->call(Object(Closure), Array)\n#5 /var/www/example.com/public_html/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(64): DI\\Definition\\Resolver\\FactoryRe in /var/www/example.com/public_html/vendor/league/flysystem/src/Adapter/Local.php on line 112, referer: https://example.com/install/
[Fri Jun 05 20:08:46.623653 2020] [php7:error] [pid 1399] [client x.x.x.x:60147] PHP Fatal error:  Uncaught League\\Flysystem\\Exception: Impossible to create the root directory "/var/www/example.com/public_html/storage". mkdir(): Permission denied in /var/www/example.com/public_html/vendor/league/flysystem/src/Adapter/Local.php:112\nStack trace:\n#0 /var/www/example.com/public_html/vendor/league/flysystem/src/Adapter/Local.php(78): League\\Flysystem\\Adapter\\Local->ensureDirectory('/var/www/lnks.d...')\n#1 /var/www/example.com/public_html/bootstrap/container.php(49): League\\Flysystem\\Adapter\\Local->__construct('/var/www/lnks.d...')\n#2 [internal function]: DI\\Definition\\Source\\DefinitionFile->{closure}(Object(DI\\Container))\n#3 /var/www/example.com/public_html/vendor/php-di/invoker/src/Invoker.php(82): call_user_func_array(Object(Closure), Array)\n#4 /var/www/example.com/public_html/vendor/php-di/php-di/src/Definition/Resolver/FactoryResolver.php(80): Invoker\\Invoker->call(Object(Closure), Array)\n#5 /var/www/example.com/public_html/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(64): DI\\Definition\\Resolver\\FactoryRe in /var/www/example.com/public_html/vendor/league/flysystem/src/Adapter/Local.php on line 112, referer: https://example.com/install/
[Fri Jun 05 20:09:07.702938 2020] [php7:error] [pid 1399] [client x.x.x.x:60168] PHP Fatal error:  Uncaught League\\Flysystem\\Exception: Impossible to create the root directory "/var/www/example.com/public_html/storage". mkdir(): Permission denied in /var/www/example.com/public_html/vendor/league/flysystem/src/Adapter/Local.php:112\nStack trace:\n#0 /var/www/example.com/public_html/vendor/league/flysystem/src/Adapter/Local.php(78): League\\Flysystem\\Adapter\\Local->ensureDirectory('/var/www/lnks.d...')\n#1 /var/www/example.com/public_html/bootstrap/container.php(49): League\\Flysystem\\Adapter\\Local->__construct('/var/www/lnks.d...')\n#2 [internal function]: DI\\Definition\\Source\\DefinitionFile->{closure}(Object(DI\\Container))\n#3 /var/www/example.com/public_html/vendor/php-di/invoker/src/Invoker.php(82): call_user_func_array(Object(Closure), Array)\n#4 /var/www/example.com/public_html/vendor/php-di/php-di/src/Definition/Resolver/FactoryResolver.php(80): Invoker\\Invoker->call(Object(Closure), Array)\n#5 /var/www/example.com/public_html/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(64): DI\\Definition\\Resolver\\FactoryRe in /var/www/example.com/public_html/vendor/league/flysystem/src/Adapter/Local.php on line 112, referer: https://example.com/install/
[Fri Jun 05 20:19:11.632691 2020] [php7:error] [pid 1464] [client x.x.x.x:60826] PHP Fatal error:  Uncaught League\\Flysystem\\Exception: Impossible to create the root directory "/var/www/example.com/public_html/storage". mkdir(): Permission denied in /var/www/example.com/public_html/vendor/league/flysystem/src/Adapter/Local.php:112\nStack trace:\n#0 /var/www/example.com/public_html/vendor/league/flysystem/src/Adapter/Local.php(78): League\\Flysystem\\Adapter\\Local->ensureDirectory('/var/www/lnks.d...')\n#1 /var/www/example.com/public_html/bootstrap/container.php(49): League\\Flysystem\\Adapter\\Local->__construct('/var/www/lnks.d...')\n#2 [internal function]: DI\\Definition\\Source\\DefinitionFile->{closure}(Object(DI\\Container))\n#3 /var/www/example.com/public_html/vendor/php-di/invoker/src/Invoker.php(82): call_user_func_array(Object(Closure), Array)\n#4 /var/www/example.com/public_html/vendor/php-di/php-di/src/Definition/Resolver/FactoryResolver.php(80): Invoker\\Invoker->call(Object(Closure), Array)\n#5 /var/www/example.com/public_html/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(64): DI\\Definition\\Resolver\\FactoryRe in /var/www/example.com/public_html/vendor/league/flysystem/src/Adapter/Local.php on line 112, referer: https://example.com/install/
```

**Comment by SergiX44** [comment]
The errors are quite obvious, the webserver has no permission to write files in that specific directory. Make the xbackbone files owned by the webserver user

**Comment by joshcsullivan** [comment]
You're right, sorry about that, so after changing permissions, the install page went through, but then it redirected to https://example.com/home but gave a 404 page not found error. Realized I had the same issue as https://github.com/SergiX44/XBackBone/issues/158, so changing apache2.conf worked for me.

Cheers!

PS. This comment is mainly for others who may run into my issue with the 404 error after install.
