### ISSUE TITLE
Screenshot

### ISSUE THREAD

**Issue by Benjjiyy** [SergiX44/XBackBone#235]
**System Info**
+ PHP Version: 7.2
+ XBackBone Version: 3.1.4
+ Webserver: [Apache/Nginx/...] idk what this is? i host with 000webhost atleast.
+ Database backend: [SQLite/Mysql/...] sqlite

**Describe the bug**
When i take a screenshot and send it to someone it doesn't show up.

**To Reproduce**
1. I take a screenshot
2. I get the link
3. I send the link to someone.

**Expected behavior**
yeah well i expected it to show up.

**Screenshots**
Thats the problem :) i cant, but heres a link to one: http://www.nosocial.life/leFu5/PUwuPUfu79.png

**Logs**
[2020-06-30 01:33:47] app.INFO: User admin logged in. [] []
[2020-06-30 01:34:49] app.INFO: User admin updated the system settings. [] []
[2020-06-30 01:34:58] app.INFO: User admin updated the system settings. [] []
[2020-06-30 01:35:04] app.INFO: User admin updated the system settings. [] []
[2020-06-30 01:35:47] app.INFO: User admin updated the system settings. [] []
[2020-06-30 01:36:05] app.INFO: User admin updated the system settings. [] []
[2020-06-30 01:36:19] app.INFO: User admin updated the system settings. [] []
[2020-06-30 01:37:28] app.INFO: User admin updated the system settings. [] []
[2020-06-30 01:37:37] app.INFO: User admin updated the system settings. [] []
[2020-06-30 01:46:20] app.ERROR: 405 Method Not Allowed
Type: Slim\Exception\HttpMethodNotAllowedException
Code: 405
Message: Method not allowed. Must be one of: GET
File: /storage/ssd3/063/14156063/public_html/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php
Line: 96
Trace: #0 /storage/ssd3/063/14156063/public_html/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(59): Slim\Middleware\RoutingMiddleware->performRouting(Object(GuzzleHttp\Psr7\ServerRequest))
#1 /storage/ssd3/063/14156063/public_html/vendor/slim/slim/Slim/MiddlewareDispatcher.php(140): Slim\Middleware\RoutingMiddleware->process(Object(GuzzleHttp\Psr7\ServerRequest), Object(class@anonymous))
#2 /storage/ssd3/063/14156063/public_html/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(98): class@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#3 /storage/ssd3/063/14156063/public_html/vendor/slim/slim/Slim/MiddlewareDispatcher.php(140): Slim\Middleware\ErrorMiddleware->process(Object(GuzzleHttp\Psr7\ServerRequest), Object(class@anonymous))
#4 /storage/ssd3/063/14156063/public_html/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): class@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#5 /storage/ssd3/063/14156063/public_html/vendor/slim/slim/Slim/App.php(211): Slim\MiddlewareDispatcher->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#6 /storage/ssd3/063/14156063/public_html/vendor/slim/slim/Slim/App.php(195): Slim\App->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#7 /storage/ssd3/063/14156063/public_html/index.php(10): Slim\App->run()
#8 {main}
Tips: To display error details in HTTP response set "displayErrorDetails" to true in the ErrorHandler constructor. [] []
[2020-06-30 01:46:21] app.ERROR: 405 Method Not Allowed
Type: Slim\Exception\HttpMethodNotAllowedException
Code: 405
Message: Method not allowed. Must be one of: GET
File: /storage/ssd3/063/14156063/public_html/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php
Line: 96
Trace: #0 /storage/ssd3/063/14156063/public_html/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(59): Slim\Middleware\RoutingMiddleware->performRouting(Object(GuzzleHttp\Psr7\ServerRequest))
#1 /storage/ssd3/063/14156063/public_html/vendor/slim/slim/Slim/MiddlewareDispatcher.php(140): Slim\Middleware\RoutingMiddleware->process(Object(GuzzleHttp\Psr7\ServerRequest), Object(class@anonymous))
#2 /storage/ssd3/063/14156063/public_html/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(98): class@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#3 /storage/ssd3/063/14156063/public_html/vendor/slim/slim/Slim/MiddlewareDispatcher.php(140): Slim\Middleware\ErrorMiddleware->process(Object(GuzzleHttp\Psr7\ServerRequest), Object(class@anonymous))
#4 /storage/ssd3/063/14156063/public_html/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): class@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#5 /storage/ssd3/063/14156063/public_html/vendor/slim/slim/Slim/App.php(211): Slim\MiddlewareDispatcher->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#6 /storage/ssd3/063/14156063/public_html/vendor/slim/slim/Slim/App.php(195): Slim\App->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#7 /storage/ssd3/063/14156063/public_html/index.php(10): Slim\App->run()
#8 {main}
Tips: To display error details in HTTP response set "displayErrorDetails" to true in the ErrorHandler constructor. [] []
[2020-06-30 01:46:51] app.INFO: User admin refreshed token of user 1. [] []
[2020-06-30 01:47:03] app.INFO: User admin uploaded new media. ["1"] []
[2020-06-30 01:47:30] app.INFO: User admin updated profile of 1. [] []
[2020-06-30 01:47:37] app.INFO: User 1, , exporting data... [] []
[2020-06-30 01:48:28] app.INFO: User admin deleted a media. [1] []
[2020-06-30 01:48:33] app.INFO: User admin uploaded new media. ["2"] []
[2020-06-30 01:48:54] app.INFO: User admin deleted a media. [2] []
[2020-06-30 01:49:19] app.INFO: User admin updated the system settings. [] []
[2020-06-30 01:49:33] app.INFO: User admin updated the system settings. [] []
[2020-06-30 01:56:14] app.INFO: User admin logged in. [] []
[2020-06-30 01:56:46] app.INFO: User admin updated the system settings. [] []
[2020-06-30 01:56:57] app.INFO: User admin updated the system settings. [] []
[2020-06-30 01:57:04] app.INFO: User admin updated the system settings. [] []
[2020-06-30 01:57:17] app.INFO: User admin updated the system settings. [] []
[2020-06-30 01:57:30] app.INFO: User admin updated the system settings. [] []
[2020-06-30 01:58:09] app.INFO: User admin updated the system settings. [] []
[2020-06-30 02:04:57] app.INFO: User 1, , exporting data... [] []
[2020-06-30 02:52:15] app.INFO: User admin uploaded new media. ["3"] []
[2020-06-30 02:53:54] app.INFO: User admin uploaded new media. ["4"] []
[2020-06-30 02:56:27] app.INFO: User admin uploaded new media. ["5"] []
[2020-06-30 02:59:25] app.INFO: User admin deleted a media. [3] []
[2020-06-30 02:59:26] app.INFO: User admin deleted a media. [4] []
[2020-06-30 02:59:26] app.INFO: User admin deleted a media. [5] []
[2020-06-30 03:00:13] app.INFO: User admin logged in. [] []
[2020-06-30 11:10:50] app.INFO: User admin logged in. [] []
[2020-06-30 11:15:15] app.INFO: User admin uploaded new media. ["6"] []

**Comment by SergiX44** [comment]
There is nothing in the logs from your webhosting?
I think it's a configuration issue on the webserver side.
