### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by StephanBruh** [SergiX44/XBackBone#250]
I switched to nginx and tried to install xbackbone again. I installed it but got an error 500. I checked the logs and it said this

```
2020/08/20 19:09:21 [error] 8557#8557: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught InvalidArgumentException: Compilation directory does not exist and cannot be created: /var/www/i.step$
Stack trace:
#0 /var/www/i.stephanbruh.nl/vendor/php-di/php-di/src/Compiler/Compiler.php(176): DI\Compiler\Compiler->createCompilationDirectory('/var/www/i.step...')
#1 /var/www/i.stephanbruh.nl/vendor/php-di/php-di/src/ContainerBuilder.php(182): DI\Compiler\Compiler->compile(Object(DI\Definition\Source\SourceChain), '/var/www/i.step...', 'CompiledContain...', 'DI\\Compil$
#2 /var/www/i.stephanbruh.nl/bootstrap/app.php(74): DI\ContainerBuilder->build()
#3 /var/www/i.stephanbruh.nl/index.php(9): require_once('/var/www/i.step...')
#4 {main}
```

does anyone have any idea? I have all the required extensions

**Comment by Pe46dro** [comment]
It seem a permission error, check if nginx user is the same that own the files

**Comment by StephanBruh** [comment]
> It seem a permission error, check if nginx user is the same that own the files

Yep that was the issue thanks!
