### ISSUE TITLE
Error: (413) Request Entity Too Large

### ISSUE THREAD

**Issue by dominikpflegerl** [SergiX44/XBackBone#260]
**System Info**
+ PHP Version: 7.3.7
Max memory usage: 128M
Max upload size:
post_max_size: 64M
upload_max_filesize: 64M
+ XBackBone Version: 3.2.0
+ Webserver: IIS 10
+ Database backend: MariaDB

Whenever I try to upload a 40 MB big MP4 file to my server, I get the following error from ShareX:

```
Error message:
The remote server returned an error: (413) Request Entity Too Large.

Request URL:
https://sh.neus.xyz/upload

Status code:
(413) Request Entity Too Large

Headers:
Connection: close
Content-Length: 67
Content-Type: text/html
Date: Sat, 19 Sep 2020 16:20:02 GMT
Server: Microsoft-IIS/10.0

Response text:
The page was not displayed because the request entity is too large.

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)
```

The Web Interface fails to show any error at all: https://sh.neus.xyz/JEjI6/LaHADoVa52.png

**Comment by dominikpflegerl** [comment]
Solved it! Issue was the IIS server with a size limit of 30 MB.

https://www.inflectra.com/support/knowledgebase/kb306.aspx
