### ISSUE TITLE
php7-tokenizer dependency

### ISSUE THREAD

**Issue by GilbN** [SergiX44/XBackBone#344]
Hi, after finishing the install wizard I got error 500 and when I checked the nginx error logs they showed this:

```
#6 /config/www/xbackbone/vendor/jeremeamia/superclosure/src/Analyzer/AstAnalyzer" while reading response header from upstream, client: 172.17.0.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost"
2021/06/05 23:27:17 [error] 339#339: *32 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Undefined constant 'T_DOUBLE_COLON' in /config/www/xbackbone/vendor/nikic/php-parser/lib/PhpParser/Lexer.php:476
Stack trace:
#0 /config/www/xbackbone/vendor/nikic/php-parser/lib/PhpParser/Lexer.php(40): PhpParser\Lexer->createTokenMap()
#1 /config/www/xbackbone/vendor/nikic/php-parser/lib/PhpParser/Lexer/Emulative.php(44): PhpParser\Lexer->__construct()
#2 /config/www/xbackbone/vendor/nikic/php-parser/lib/PhpParser/ParserFactory.php(23): PhpParser\Lexer\Emulative->__construct()
#3 /config/www/xbackbone/vendor/jeremeamia/superclosure/src/Analyzer/AstAnalyzer.php(143): PhpParser\ParserFactory->create()
#4 /config/www/xbackbone/vendor/jeremeamia/superclosure/src/Analyzer/AstAnalyzer.php(134): SuperClosure\Analyzer\AstAnalyzer->getParser()
#5 /config/www/xbackbone/vendor/jeremeamia/superclosure/src/Analyzer/AstAnalyzer.php(55): SuperClosure\Analyzer\AstAnalyzer->getFileAst()
#6 /config/www/xbackbone/vendor/jeremeamia/superclosure/src/Analyzer/AstAnalyzer" while reading response header from upstream, client: 172.17.0.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost"
```

But after I added `php7-tokenizer` everything worked just fine. I'm on  alpine:3.12 so might just be that, but if it's a dependency the docs are missing it :)

**Comment by SergiX44** [comment]
Thanks!
that strange actually, the tokenizer extension should be int the core and enable by default, maybe on alpine the php packages are stripped down.
I'll update the docs.
