### ISSUE TITLE
use_path_style_endpoint does not work

### ISSUE THREAD

**Issue by kgnfth** [SergiX44/XBackBone#369]
**System Info**
+ PHP Version: `7.4.21`
+ XBackBone Version: `3.4.1`
+ Webserver: `nginx proxy`
+ Database backend: `Mariadb`

**Describe the bug**
When using minio as S3-compatible, i set my config like this
```
  'storage' => array (
      'driver' => 's3',
      'endpoint' => 'https://minio.redacted.fun:9000',
      'key' => 'redacted',
      'secret' => 'redacted',
      'region' => 'eu-east-1',
      'bucket' => 'xbb',
      'path' => '/',
      'use_path_style_endpoint' => true,
  ),
```
But the app keeps adding the bucket-name as a subdomain eg `https://xbb.minio.redacted.fun:9000`
which gives me the error
`Message: Connection refused for URI https://xbb.minio.redacted.fun:9000/?prefix=jufE8%2FlELIqEXA12.png%2F&amp;max-keys=1&amp;encoding-type=url`

**Logs**
```
Type: GuzzleHttp\Exception\ConnectException
Code: 0
Message: Connection refused for URI https://xbb.minio.redacted.fun:9000/?prefix=jufE8%2FlELIqEXA12.png%2F&amp;max-keys=1&amp;encoding-type=url
File: /config/www/xbackbone/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php
Line: 321
Trace: #0 /config/www/xbackbone/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php(240): GuzzleHttp\Handler\StreamHandler->GuzzleHttp\Handler\{closure}()
#1 /config/www/xbackbone/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php(332): GuzzleHttp\Handler\StreamHandler->createResource()
#2 /config/www/xbackbone/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php(58): GuzzleHttp\Handler\StreamHandler->createStream()
#3 /config/www/xbackbone/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(35): GuzzleHttp\Handler\StreamHandler->__invoke()
#4 /config/www/xbackbone/vendor/guzzlehttp/guzzle/src/Middleware.php(31): GuzzleHttp\PrepareBodyMiddleware->__invoke()
#5 /config/www/xbackbone/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(71): GuzzleHttp\Middleware::GuzzleHttp\{closure}()
#6 /config/www/xbackbone/vendor/guzzlehttp/guzzle/src/Middleware.php(63): GuzzleHttp\RedirectMiddleware->__invoke()
#7 /config/www/xbackbone/vendor/guzzlehttp/guzzle/src/HandlerStack.php(75): GuzzleHttp\Middleware::GuzzleHttp\{closure}()
#8 /config/www/xbackbone/vendor/guzzlehttp/guzzle/src/Client.php(331): GuzzleHttp\HandlerStack->__invoke()
#9 /config/www/xbackbone/vendor/guzzlehttp/guzzle/src/Client.php(107): GuzzleHttp\Client->transfer()
#10 /config/www/xbackbone/vendor/aws/aws-sdk-php/src/Handler/GuzzleV6/GuzzleHandler.php(43): GuzzleHttp\Client->sendAsync()
#11 /config/www/xbackbone/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php(87): Aws\Handler\GuzzleV6\GuzzleHandler->__invoke()
#12 /config/www/xbackbone/vendor/aws/aws-sdk-php/src/ClientSideMonitoring/AbstractMonitoringMiddleware.php(126): Aws\WrappedHttpHandler->__invoke()
#13 /config/www/xbackbone/vendor/aws/aws-sdk-php/src/S3/PermanentRedirectMiddleware.php(43): Aws\ClientSideMonitoring\AbstractMonitoringMiddleware->__invoke()
#14 /config/www/xbackbone/vendor/aws/aws-sdk-php/src/S3/PutObjectUrlMiddleware.php(41): Aws\S3\PermanentRedirectMiddleware->__invoke()
#15 /config/www/xbackbone/vendor/aws/aws-sdk-php/src/Middleware.php(126): Aws\S3\PutObjectUrlMiddleware->__invoke()
#16 /config/www/xbackbone/vendor/guzzlehttp/promises/src/FulfilledPromise.php(41): Aws\Middleware::Aws\{closure}()
#17 /config/www/xbackbone/vendor/guzzlehttp/promises/src/TaskQueue.php(48): GuzzleHttp\Promise\FulfilledPromise::GuzzleHttp\Promise\{closure}()
#18 /config/www/xbackbone/vendor/guzzlehttp/promises/src/Promise.php(248): GuzzleHttp\Promise\TaskQueue->run()
#19 /config/www/xbackbone/vendor/guzzlehttp/promises/src/Promise.php(224): GuzzleHttp\Promise\Promise->invokeWaitFn()
#20 /config/www/xbackbone/vendor/guzzlehttp/promises/src/Promise.php(269): GuzzleHttp\Promise\Promise->waitIfPending()
#21 /config/www/xbackbone/vendor/guzzlehttp/promises/src/Promise.php(226): GuzzleHttp\Promise\Promise->invokeWaitList()
#22 /config/www/xbackbone/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
#23 /config/www/xbackbone/vendor/aws/aws-sdk-php/src/AwsClientTrait.php(58): GuzzleHttp\Promise\Promise->wait()
#24 /config/www/xbackbone/vendor/league/flysystem-aws-s3-v3/src/AwsS3Adapter.php(711): Aws\AwsClient->execute()
#25 /config/www/xbackbone/vendor/league/flysystem-aws-s3-v3/src/AwsS3Adapter.php(237): League\Flysystem\AwsS3v3\AwsS3Adapter->doesDirectoryExist()
#26 /config/www/xbackbone/vendor/league/flysystem/src/Filesystem.php(58): League\Flysystem\AwsS3v3\AwsS3Adapter->has()
#27 /config/www/xbackbone/vendor/league/flysystem/src/Filesystem.php(405): League\Flysystem\Filesystem->has()
#28 /config/www/xbackbone/vendor/league/flysystem/src/Filesystem.php(83): League\Flysystem\Filesystem->assertAbsent()
#29 /config/www/xbackbone/app/Controllers/UploadController.php(192): League\Flysystem\Filesystem->writeStream()
#30 /config/www/xbackbone/app/Controllers/UploadController.php(62): App\Controllers\UploadController->saveMedia()
#31 [internal function]: App\Controllers\UploadController->uploadWeb()
#32 /config/www/xbackbone/vendor/php-di/invoker/src/Invoker.php(82): call_user_func_array()
#33 /config/www/xbackbone/vendor/php-di/slim-bridge/src/ControllerInvoker.php(47): Invoker\Invoker->call()
#34 /config/www/xbackbone/vendor/slim/slim/Slim/Routing/Route.php(384): DI\Bridge\Slim\ControllerInvoker->__invoke()
#35 /config/www/xbackbone/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\Routing\Route->handle()
#36 /config/www/xbackbone/app/Middleware/CheckForMaintenanceMiddleware.php(26): Slim\MiddlewareDispatcher->handle()
#37 /config/www/xbackbone/vendor/slim/slim/Slim/MiddlewareDispatcher.php(268): App\Middleware\CheckForMaintenanceMiddleware->__invoke()
#38 /config/www/xbackbone/app/Middleware/AuthMiddleware.php(33): class@anonymous->handle()
#39 /config/www/xbackbone/vendor/slim/slim/Slim/MiddlewareDispatcher.php(268): App\Middleware\AuthMiddleware->__invoke()
#40 /config/www/xbackbone/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): class@anonymous->handle()
#41 /config/www/xbackbone/vendor/slim/slim/Slim/Routing/Route.php(341): Slim\MiddlewareDispatcher->handle()
#42 /config/www/xbackbone/vendor/slim/slim/Slim/Routing/RouteRunner.php(84): Slim\Routing\Route->run()
#43 /config/www/xbackbone/app/Middleware/InjectMiddleware.php(21): Slim\Routing\RouteRunner->handle()
#44 /config/www/xbackbone/vendor/slim/slim/Slim/MiddlewareDispatcher.php(268): App\Middleware\InjectMiddleware->__invoke()
#45 /config/www/xbackbone/app/Middleware/LangMiddleware.php(25): class@anonymous->handle()
#46 /config/www/xbackbone/vendor/slim/slim/Slim/MiddlewareDispatcher.php(268): App\Middleware\LangMiddleware->__invoke()
#47 /config/www/xbackbone/app/Middleware/RememberMiddleware.php(39): class@anonymous->handle()
#48 /config/www/xbackbone/vendor/slim/slim/Slim/MiddlewareDispatcher.php(268): App\Middleware\RememberMiddleware->__invoke()
#49 /config/www/xbackbone/bootstrap/app.php(105): class@anonymous->handle()
#50 /config/www/xbackbone/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Closure->{closure}()
#51 /config/www/xbackbone/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(59): class@anonymous->handle()
#52 /config/www/xbackbone/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\RoutingMiddleware->process()
#53 /config/www/xbackbone/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(107): class@anonymous->handle()
#54 /config/www/xbackbone/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\ErrorMiddleware->process()
#55 /config/www/xbackbone/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): class@anonymous->handle()
#56 /config/www/xbackbone/vendor/slim/slim/Slim/App.php(215): Slim\MiddlewareDispatcher->handle()
#57 /config/www/xbackbone/vendor/slim/slim/Slim/App.php(199): Slim\App->handle()
#58 /config/www/xbackbone/index.php(11): Slim\App->run()
#59 {main}
```

**Comment by SergiX44** [comment]
It's because that config is not passed through when creating the S3 client, can you try to add that here? https://github.com/SergiX44/XBackBone/blob/master/bootstrap/container.php#L61
 If it works I'll provide a config in the next release

**Comment by kgnfth** [comment]
still the same issue

**Comment by SergiX44** [comment]
Try to clear the cache using the script in bin/
All the container instances are cached to speedup the app bootstrap.

**Comment by kgnfth** [comment]
still the same
i am running it in docker btw, and used the docker shell to clean
i tried `php clean cache` and `php clean all`

**Comment by SergiX44** [comment]
> still the same
> i am running it in docker btw, and used the docker shell to clean
> i tried `php clean cache` and `php clean all`
> 
> EDIT:
> i redployed XBB and when i was at /install i added `'use_path_style_endpoint' => true,`
> to container.php
> now everything works !

Thanks, I'll fix that in the next release
