### ISSUE TITLE
Installation Error (500)

### ISSUE THREAD

**Issue by ahunt0** [SergiX44/XBackBone#399]
**System Info**
+ PHP Version: 7.4
+ XBackBone Version:  3.5.0
+ Webserver: Apache
+ Database backend: MySQL

**Describe the bug**
Upon install, I get a server error (500). I'm using MySQL, for the database and for storage I'm using local.
I don't think it's file permissions, but I could be wrong. Seems like it's an issue with MySQL.

**Logs**
```
[Mon Oct 18 14:59:53.768394 2021] [fcgid:warn] [pid 2967814:tid 140232687085312] [client 172.70.126.15:34968] mod_fcgid: stderr: PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [1045] Access denied for user 'impala'@'localhost' (using password: YES) in /home/clown/domains/i.clown.pw/public_html/app/Database/DB.php:20, referer: https://i.clown.pw/install/
[Mon Oct 18 14:59:53.768418 2021] [fcgid:warn] [pid 2967814:tid 140232687085312] [client 172.70.126.15:34968] mod_fcgid: stderr: Stack trace:, referer: https://i.clown.pw/install/
[Mon Oct 18 14:59:53.768420 2021] [fcgid:warn] [pid 2967814:tid 140232687085312] [client 172.70.126.15:34968] mod_fcgid: stderr: #0 /home/clown/domains/i.clown.pw/public_html/app/Database/DB.php(20): PDO->__construct(), referer: https://i.clown.pw/install/
[Mon Oct 18 14:59:53.768422 2021] [fcgid:warn] [pid 2967814:tid 140232687085312] [client 172.70.126.15:34968] mod_fcgid: stderr: #1 /home/clown/domains/i.clown.pw/public_html/bootstrap/container.php(43): App\\Database\\DB->__construct(), referer: https://i.clown.pw/install/
[Mon Oct 18 14:59:53.768424 2021] [fcgid:warn] [pid 2967814:tid 140232687085312] [client 172.70.126.15:34968] mod_fcgid: stderr: #2 [internal function]: DI\\Definition\\Source\\DefinitionFile->{closure}(), referer: https://i.clown.pw/install/
[Mon Oct 18 14:59:53.768426 2021] [fcgid:warn] [pid 2967814:tid 140232687085312] [client 172.70.126.15:34968] mod_fcgid: stderr: #3 /home/clown/domains/i.clown.pw/public_html/vendor/php-di/invoker/src/Invoker.php(82): call_user_func_array(), referer: https://i.clown.pw/install/
[Mon Oct 18 14:59:53.768428 2021] [fcgid:warn] [pid 2967814:tid 140232687085312] [client 172.70.126.15:34968] mod_fcgid: stderr: #4 /home/clown/domains/i.clown.pw/public_html/vendor/php-di/php-di/src/Definition/Resolver/FactoryResolver.php(80): Invoker\\Invoker->call(), referer: https://i.clown.pw/install/
[Mon Oct 18 14:59:53.768430 2021] [fcgid:warn] [pid 2967814:tid 140232687085312] [client 172.70.126.15:34968] mod_fcgid: stderr: #5 /home/clown/domains/i.clown.pw/public_html/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(71): DI\\Definition\\Resolver\\FactoryResolver->resolve(), referer: https://i.clown.pw/install/
[Mon Oct 18 14:59:53.768432 2021] [fcgid:warn] [pid 2967814:tid 140232687085312] [client 172.70.126.15:34968] mod_fcgid: stderr: #6 /home/clown/domains/i.clown.pw/public_html/vendor/php-di/php-di/src/Container.php(387): DI\\Definition\\Resolver\\ResolverDispatcher->resolv in /home/clown/domains/i.clown.pw/public_html/app/Database/DB.php on line 20, referer: https://i.clown.pw/install/
```

**Comment by clownmoney** [comment]
Solved, was using a database login that had no permissions essentially, so it couldn't do anything.
