### ISSUE TITLE
php bin/migrate --install error

### ISSUE THREAD

**Issue by TurboCheetah** [SergiX44/XBackBone#5]
When I run `php bin/migrate --install` I get this output:
```PHP Fatal error:  Uncaught PDOException: could not find driver in /redacted/filehost/app/Database/DB.php:32
Stack trace:
#0 /redacted/filehost/app/Database/DB.php(32): PDO->__construct('sqlite:resource...', NULL, NULL)
#1 /redacted/filehost/app/Database/DB.php(82): App\Database\DB->__construct('sqlite:resource...', NULL, NULL)
#2 /redacted/filehost/bin/migrate(21): App\Database\DB::driver()
#3 {main}
  thrown in/redacted/filehost/app/Database/DB.php on line 32
```

**Comment by SergiX44** [comment]
Can you provide logs? Have you followed the install guide?

**Comment by byRoadrunner** [comment]
Did you find a solution for this @TurboCheetah .  Because I am facing this issue too.

**Comment by TurboCheetah** [comment]
No I did not.

@SergiX44

**Comment by SergiX44** [comment]
Can you provide logs, environment and php version?
With a simple screen of the problem I cannot reproduce the bug...

**Comment by byRoadrunner** [comment]
I´ve tried with PHP Version 7.2 and 7.1, I dont see any errors in the logs, it just redirects me to /login and then wants me to download this file.

**Comment by SergiX44** [comment]
Can you provide the request headers and the precise steps to reproduce it?
I've just tried a fresh install on my server and it works without problems. I still cannot reproduce the bug.
