### ISSUE TITLE
Internal Server Error on user modification

### ISSUE THREAD

**Issue by BeerGrizzly** [SergiX44/XBackBone#64]
**System Info**
+ PHP Version: 7.3.5
+ XBackBone Version: 2.6
+ Webserver: NGINX

**Describe the bug**
When editing or creating a user account i get an Internal Server Error. The logs say the database is read-only which shouldn't be as i set the owner to www-data.

**To Reproduce**
As stated in the recent issue #62 

**Expected behavior**
The user data to be updated/saved

**Screenshots**
![chrome_7jIAYFhDg9](https://user-images.githubusercontent.com/37215927/64049597-9f8de700-cb75-11e9-8d09-c81176470f6a.png)

**Logs**
```
[2019-08-30 22:25:38] app.INFO: User admin logged in. [] []
[2019-08-30 22:26:10] app.CRITICAL: Fatal exception during app execution {"exception":"[object] (PDOException(code: HY000): SQLSTATE[HY000]: General error: 8 attempt to write a readonly database at /var/www/felix.beer/html/share/app/Database/DB.php:54)
[stacktrace]
#0 /var/www/felix.beer/html/share/app/Database/DB.php(54): PDOStatement->execute()
#1 /var/www/felix.beer/html/share/app/Controllers/UserController.php(173): App\\Database\\DB->query(Object(PDOStatement), Array)
#2 [internal function]: App\\Controllers\\UserController->update(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Array)
#3 /var/www/felix.beer/html/share/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(41): call_user_func(Array, Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Array)
#4 /var/www/felix.beer/html/share/vendor/slim/slim/Slim/Route.php(356): Slim\\Handlers\\Strategies\\RequestResponse->__invoke(Array, Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Array)
#5 /var/www/felix.beer/html/share/app/Middleware/AdminMiddleware.php(25): Slim\\Route->__invoke(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))
#6 [internal function]: App\\Middleware\\AdminMiddleware->__invoke(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Object(Slim\\Route))
#7 /var/www/felix.beer/html/share/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array(Array, Array)
#8 [internal function]: Slim\\DeferredCallable->__invoke(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Object(Slim\\Route))
#9 /var/www/felix.beer/html/share/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\\DeferredCallable), Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Object(Slim\\Route))
#10 /var/www/felix.beer/html/share/app/Middleware/CheckForMaintenanceMiddleware.php(24): Slim\\Route->Slim\\{closure}(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))
#11 [internal function]: App\\Middleware\\CheckForMaintenanceMiddleware->__invoke(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Object(Closure))
#12 /var/www/felix.beer/html/share/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array(Array, Array)
#13 [internal function]: Slim\\DeferredCallable->__invoke(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Object(Closure))
#14 /var/www/felix.beer/html/share/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\\DeferredCallable), Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Object(Closure))
#15 /var/www/felix.beer/html/share/app/Middleware/AuthMiddleware.php(31): Slim\\Route->Slim\\{closure}(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))
#16 [internal function]: App\\Middleware\\AuthMiddleware->__invoke(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Object(Closure))
#17 /var/www/felix.beer/html/share/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array(Array, Array)
#18 [internal function]: Slim\\DeferredCallable->__invoke(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Object(Closure))
#19 /var/www/felix.beer/html/share/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\\DeferredCallable), Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Object(Closure))
#20 /var/www/felix.beer/html/share/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\\Route->Slim\\{closure}(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))
#21 /var/www/felix.beer/html/share/vendor/slim/slim/Slim/Route.php(334): Slim\\Route->callMiddlewareStack(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))
#22 /var/www/felix.beer/html/share/vendor/slim/slim/Slim/App.php(515): Slim\\Route->run(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))
#23 /var/www/felix.beer/html/share/bootstrap/app.php(216): Slim\\App->__invoke(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))
#24 [internal function]: Closure->{closure}(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Object(Slim\\App))
#25 /var/www/felix.beer/html/share/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array(Object(Closure), Array)
#26 [internal function]: Slim\\DeferredCallable->__invoke(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Object(Slim\\App))
#27 /var/www/felix.beer/html/share/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\\DeferredCallable), Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Object(Slim\\App))
#28 /var/www/felix.beer/html/share/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\\App->Slim\\{closure}(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))
#29 /var/www/felix.beer/html/share/vendor/slim/slim/Slim/App.php(405): Slim\\App->callMiddlewareStack(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))
#30 /var/www/felix.beer/html/share/vendor/slim/slim/Slim/App.php(313): Slim\\App->process(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))
#31 /var/www/felix.beer/html/share/index.php(9): Slim\\App->run()
#32 {main}
"} []```

**Comment by SergiX44** [comment]
Please check that the xbackbone.db file is owned by the web server user.
If you have installed it via cli as root, the db file will be owned by the root user.

**Comment by BeerGrizzly** [comment]
I already did that as stated in the 'Describe the bug' section:
The logs say the database is read-only which shouldn't be as i set the owner to www-data.

**Comment by SergiX44** [comment]
I've tested on a clean lemp vps on digitalocean (nginx + php7.2), php-fpm and nginx use www-data:
+ Downloaded and unzipped the release.
+ Adjusted the nginx config
+ cp `config.example.php` to `config.php`
+ chown `www-data` on the whole document root
+ Run `bin/migrate` script

Now if I login and I try to create a user, it gives me the error because the file in `resource/database/xbackbone.db` is owned by root.
+ chown to www-data the `resource/database/xbackbone.db` file.
Now the write query are working (create user, upload, etc).

Check that php-fpm daemon and nginx are actually configured to use the www-data user, or fix the file permissions accordingly.

**Comment by BeerGrizzly** [comment]
Thanks! I somehow made a mistake when trying to chown to the db file, really sorry for taking so much of your time.
