### ISSUE TITLE
Config import does not work

### ISSUE THREAD

**Issue by gerroon** [SergiX44/XBackBone#68]
**System Info**
+ PHP Version:
`Configuration File (php.ini) Path 	/etc/php/7.1/apache2 `

+ XBackBone Version:
2.6

+ Webserver:
Apache/2.4.41 (Debian) 

**Describe the bug**
I installed Xbackboen using Docker, then I reverse proxied it. The backend seems to work, I am able to login, create users, download Sharex config. The issue happens inside sharex, I import the config from Xbackbone then test the uploaders, and all seem to throw these errors

At this point I d onot know if this is an issue for this Xbackbone or ShareX. Let me know if this is a ShareX issue I will file it there too.

```

Error message:
The remote server returned an error: (500) Internal Server Error.

Request URL:
https://DOMAIN/myshare/upload

Status code:
500 InternalServerError

Headers:
Pragma: no-cache
Connection: close
Content-Length: 2684
Cache-Control: no-store, no-cache, must-revalidate
Content-Type: text/html; charset=UTF-8
Date: Fri, 13 Sep 2019 21:09:41 GMT
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Set-Cookie: xbackbone_session=h8hsnfb358g9g52a2m5gko7pdf; path=/; HttpOnly
Server: nginx/1.14.2

Response text:
<!doctype html>
<html lang="">
<head>
    <title>Internal Server Error | XBackBone</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, myshareink-to-fit=no">
    <meta name="description" content="XBackBone is a simple and lightweight PHP backend for ShareX">
    <link rel="shortcut icon" href="https://DOMAIN/myshare/favicon.ico" type="image/x-icon">
    <link rel="icon" href="https://DOMAIN/myshare/favicon.ico" type="image/x-icon">
    <link rel="preload" href="https://DOMAIN/myshare/static/bootstrap/css/bootstrap.min.css" as="style">
    <link rel="preload" href="https://DOMAIN/myshare/static/app/app.css" as="style">
    <link rel="preload" href="https://DOMAIN/myshare/static/jquery/jquery.min.js" as="script">
    <link rel="preload" href="https://DOMAIN/myshare/static/bootstrap/js/bootstrap.bundle.min.js" as="script">
    <link rel="preload" href="https://DOMAIN/myshare/static/fontawesome/js/all.min.js" as="script">
    <link rel="preload" href="https://DOMAIN/myshare/static/app/app.js" as="script">
    <link href="https://DOMAIN/myshare/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://DOMAIN/myshare/static/highlightjs/styles/monokai.css" rel="stylesheet">
    <link href="https://DOMAIN/myshare/static/videojs/video-js.min.css" rel="stylesheet">
    <link href="https://DOMAIN/myshare/static/app/app.css" rel="stylesheet">
    <script src="https://DOMAIN/myshare/static/jquery/jquery.min.js"></script>
    <script src="https://DOMAIN/myshare/static/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="https://DOMAIN/myshare/static/fontawesome/js/all.min.js"></script>
    <script src="https://DOMAIN/myshare/static/highlightjs/highlight.pack.min.js"></script>
    <script src="https://DOMAIN/myshare/static/clipboardjs/clipboard.min.js"></script>
    <script src="https://DOMAIN/myshare/static/videojs/video.min.js"></script>
    <script src="https://DOMAIN/myshare/static/app/app.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>
    <script>window.AppConfig = {'base_url': 'https://DOMAIN/myshare', 'lang': {'publish': 'Publish', 'hide': 'Hide'}}</script>
    </head>
<body>
    <div class="container-fluid mt-5">
        <div class="text-center">
            <div class="row">
                <div class="col-md-12">
                    <h1 class="display-1">500 Internal Server Error</h1>
                    <p class="lead">Unexpected error while handling the request.</p>
                </div>
            </div>
        </div>
            </div>
</body>
</html>


Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)



```

**Comment by gerroon** [comment]
Here is the log from the Docker


````
019/09/13 23:36:36 [warn] 69#69: *36 a client request body is buffered to a temporary file /var/tmp/nginx/client_body/0000000009, client: 172.17.0.1, server: _, request: "POST /upload HTTP/1.1", host: "127.0.0.1:8087"
[13-Sep-2019 23:36:36] WARNING: [pool www] child 77 said into stderr: "NOTICE: PHP message: PHP Notice:  Undefined index: HTTP_ACCEPT_LANGUAGE in /app/app/Web/Lang.php on line 61"          
[13-Sep-2019 23:36:36] WARNING: [pool www] child 77 said into stderr: "NOTICE: PHP message: PHP Warning:  array_key_exists(): The first argument should be either a string or an integer in /app/app/Web/Lang.php on line 114"
[13-Sep-2019 23:36:36] WARNING: [pool www] child 77 said into stderr: "NOTICE: PHP message: PHP Warning:  array_key_exists(): The first argument should be either a string or an integer in /app/app/Web/Lang.php on line 114"
[php-fpm:access] 127.0.0.1 -  13/Sep/2019:23:36:36 +0000 "POST /index.php" 500 /app/index.php 8.993 2048 0.00%                                                                               
2019/09/13 23:36:36 [error] 69#69: *36 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: HTTP_ACCEPT_LANGUAGE in /app/app/Web/Lang.php on line 61                          
PHP message: PHP Warning:  array_key_exists(): The first argument should be either a string or an integer in /app/app/Web/Lang.php on line 114                                               
PHP message: PHP Warning:  array_key_exists(): The first argument should be either a string or an integer in /app/app/Web/Lang.php on line 114" while reading response header from upstream, client: 172.17.0.1, server: _, request: "POST /upload HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "127.0.0.1:8087"                                                                 
172.17.0.1 - - [13/Sep/2019:23:36:36 +0000] "POST /upload HTTP/1.1" 500 2684 "-" "ShareX/13.0.2"                                                                                             
2019/09/13 23:36:36 [warn] 69#69: *38 a client request body is buffered to a temporary file /var/tmp/nginx/client_body/0000000010, client: 172.17.0.1, server: _, request: "POST /upload HTTP/1.1", host: "127.0.0.1:8087"
[13-Sep-2019 23:36:36] WARNING: [pool www] child 78 said into stderr: "NOTICE: PHP message: PHP Notice:  Undefined index: HTTP_ACCEPT_LANGUAGE in /app/app/Web/Lang.php on line 61"          
[13-Sep-2019 23:36:36] WARNING: [pool www] child 78 said into stderr: "NOTICE: PHP message: PHP Warning:  array_key_exists(): The first argument should be either a string or an integer in /app/app/Web/Lang.php on line 114"
[13-Sep-2019 23:36:36] WARNING: [pool www] child 78 said into stderr: "NOTICE: PHP message: PHP Warning:  array_key_exists(): The first argument should be either a string or an integer in /app/app/Web/Lang.php on line 114"
[php-fpm:access] 127.0.0.1 -  13/Sep/2019:23:36:36 +0000 "POST /index.php" 500 /app/index.php 12.141 2048 164.73%                                                                            
2019/09/13 23:36:36 [error] 69#69: *38 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: HTTP_ACCEPT_LANGUAGE in /app/app/Web/Lang.php on line 61                          
PHP message: PHP Warning:  array_key_exists(): The first argument should be either a string or an integer in /app/app/Web/Lang.php on line 114                                               
PHP message: PHP Warning:  array_key_exists(): The first argument should be either a string or an integer in /app/app/Web/Lang.php on line 114" while reading response header from upstream, client: 172.17.0.1, server: _, request: "POST /upload HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "127.0.0.1:8087"                                                                 
172.17.0.1 - - [13/Sep/2019:23:36:36 +0000] "POST /upload HTTP/1.1" 500 2684 "-" "ShareX/13.0.2"                                                                                             

───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────


```

**Comment by gerroon** [comment]
Here another error from Docker log, this time I am trying to use the Linux script instead of Sharex

```
2019/09/14 00:43:39 [warn] 69#69: *90 a client request body is buffered to a temporary file /var/tmp/nginx/client_body/0000000014, client: 172.17.0.1, server: _, request: "POST /upload HTTP/1.1", host: "127.0.0.1:8087"
[14-Sep-2019 00:43:40] WARNING: [pool www] child 78 said into stderr: "NOTICE: PHP message: PHP Notice:  Trying to get property 'is_admin' of non-object in /app/app/Controllers/UploadController.php on line 32"
[php-fpm:access] 127.0.0.1 -  14/Sep/2019:00:43:40 +0000 "POST /index.php" 503 /app/index.php 39.118 2048 102.25%
2019/09/14 00:43:40 [error] 69#69: *90 FastCGI sent in stderr: "PHP message: PHP Notice:  Trying to get property 'is_admin' of non-object in /app/app/Controllers/UploadController.php on line 32" while reading response header from upstream, client: 172.17.0.1, server: _, request: "POST /upload HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "127.0.0.1:8087"
172.17.0.1 - - [14/Sep/2019:00:43:40 +0000] "POST /upload HTTP/1.1" 503 84 "-" "curl/7.65.3"
```

**Comment by SergiX44** [comment]
I'm not the manteiner of the docker image, please report this issue in the docker image repository.

**Comment by gerroon** [comment]
@Pe46dro does this look like the Docker install issue? if so I will reopen it in your repo.

**Comment by Pe46dro** [comment]
The problem seems to be related to apache proxy configuration that maybe (?) don't forward HTTP_ACCEPT_LANGUAGE correctly to Docker container, I have made a PR (#69) to fix the notice and the warning.

**Comment by gerroon** [comment]
Thanks
