### ISSUE TITLE
Class 'finfo' not found

### ISSUE THREAD

**Issue by AmSyyc** [SergiX44/XBackBone#76]
On PHP version 7.3.

After screenshotting and going to the link, it then provides a "500" error.

```
#0 /home/srspxoem/public_html/i2/vendor/league/flysystem/src/Filesystem.php(285): League\Flysystem\Adapter\Local->getMimetype('qAYO6/tOviloHoT...')

#1 /home/srspxoem/public_html/i2/app/Controllers/UploadController.php(113): League\Flysystem\Filesystem->getMimetype('qAYO6/tOviloHoT...')

#2 [internal function]: App\Controllers\UploadController->show(Object(Slim\Http\Request), Object(Slim\Http\Response), Array)

#3 /home/srspxoem/public_html/i2/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(40): call_user_func(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array)

#4 /home/srspxoem/public_html/i2/vendor/slim/slim/Slim/Route.php(281): Slim\Handlers\Strategies\RequestResponse->__invoke(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array)

#5 /home/srspxoem/public_html/i2/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))

#6 /home/srspxoem/public_html/i2/vendor/slim/slim/Slim/Route.php(268): Slim\Route->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))

#7 /home/srspxoem/public_html/i2/vendor/slim/slim/Slim/App.php(503): Slim\Route->run(Object(Slim\Http\Request), Object(Slim\Http\Response))

#8 /home/srspxoem/public_html/i2/bootstrap/app.php(219): Slim\App->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))

#9 [internal function]: Closure->{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\App))

#10 /home/srspxoem/public_html/i2/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(Closure), Array)

#11 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\App))

#12 /home/srspxoem/public_html/i2/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\App))

#13 /home/srspxoem/public_html/i2/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response))

#14 /home/srspxoem/public_html/i2/vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))

#15 /home/srspxoem/public_html/i2/vendor/slim/slim/Slim/App.php(297): Slim\App->process(Object(Slim\Http\Request), Object(Slim\Http\Response))

#16 /home/srspxoem/public_html/i2/index.php(9): Slim\App->run()

#17 {main}
```

Above that, the specified error is:
> Class 'finfo' not found (Line 319 in file /home/srspxoem/public_html/i2/vendor/league/flysystem/src/Adapter/Local.php)

Another thing I have noticed is it provides the same error on the index page.
Am I missing something?

**Comment by SergiX44** [comment]
The fileinfo module in your Php installation is missing, try to install it via your package manager or enable it.

**Comment by AmSyyc** [comment]
> The fileinfo module in your Php installation is missing, try to install it via your package manager or enable it.

Solved, thanks!
